### ISSUE TITLE
Reference state

### ISSUE THREAD

**Issue by sparkyslug** [JorisCaze/NASG-EOS_Calibration#1]
Perhaps I am missing something, but for your oxygen example it seems the reference state (refState.txt) is not consistent with the reference state for the enthalpy values of the fluid and gas. I would expect the enthalpy for the fluid to be 0 at the reference state which I think is 90 K; .09935 MPa. In the expData.txt file the enthalpy at 90 K; 0.9935 MPa is -133525 J/kg. 

I am trying to replicate your method with methane and am getting errors. Am I overlooking something?

**Comment by JorisCaze** [comment]
Dear @sparkyslug, 

The values given in the *refState.txt* file are taken from the [NIST database](https://webbook.nist.gov/cgi/fluid.cgi?TLow=90&THigh=90&TInc=&Digits=5&ID=C7782447&Action=Load&Type=SatP&TUnit=K&PUnit=MPa&DUnit=kg%2Fm3&HUnit=kJ%2Fkg&WUnit=m%2Fs&VisUnit=uPa*s&STUnit=N%2Fm&RefState=DEF) and are consistent with the values given in the article *[Le Métayer et al., 2016](https://aip.scitation.org/doi/10.1063/1.4945981)* (see page 15).

It is not required to have an enthalpy of 0 for the reference state, see water calibration for example.
For more information on the choice of the reference state, it is highly recommended to read the following articles:
- [Le Métayer et al., 2004](https://doi.org/10.1016/j.ijthermalsci.2003.09.002)
- [Le Métayer et al., 2016](https://aip.scitation.org/doi/10.1063/1.4945981)

What type of errors do you encounter?
Most of the time, an error is encountered when the specified temperature interval is too large to allow calibration of the equation of state (EOS). This is because the EOS is no longer valid in that interval (which causes the least squares fit to fail).

I had good results in the past for the calibration of methane for a temperature range of about [90-150] K with a reference state defined at about 110 K with experimental data from the [NIST database](https://webbook.nist.gov/cgi/fluid.cgi?TLow=&THigh=&TInc=&Digits=5&ID=C74828&Action=Load&Type=SatP&TUnit=K&PUnit=MPa&DUnit=kg%2Fm3&HUnit=kJ%2Fkg&WUnit=m%2Fs&VisUnit=uPa*s&STUnit=N%2Fm&RefState=DEF).
<img width="862" alt="image" src="https://user-images.githubusercontent.com/38508580/207411544-8d6bbe45-42a4-42db-97c0-f3b00a97c5c3.png">
<img width="862" alt="image" src="https://user-images.githubusercontent.com/38508580/207411613-355b8583-6369-432f-a756-2c871133f5ce.png">
<img width="862" alt="image" src="https://user-images.githubusercontent.com/38508580/207411672-85ba520f-b5ad-437d-8eca-8536c1d35828.png">


Best regards, 
Joris

**Comment by sparkyslug** [comment]
Thank you,

We were able to get a decent fit when we reduced the temperature range. As
you indicated, that was probably the issue. Thank you for responding.
